// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const dotenv = require("dotenv");
dotenv.config();    
const { defineConfig, env } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});


